# Generated by Django 3.2.9 on 2021-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
