# Generated by Django 4.0.1 on 2022-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='lname',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='ppic',
            field=models.ImageField(default='404Error.jpg', null=True, upload_to='<django.db.models.fields.related.OneToOneField>_pp.jpg'),
        ),
    ]
