# Generated by Django 4.0.1 on 2022-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_remove_authuser_fname_remove_authuser_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='ppic',
            field=models.ImageField(default='Default_PP.jpg', null=True, upload_to='<django.db.models.fields.related.OneToOneField>_pp.jpg'),
        ),
    ]
