# Generated by Django 3.2.9 on 2021-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_orders_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(on_delete=models.SET('Previous Orders'), to='Home.cart'),
        ),
    ]
